name: veropt
channels:
  - conda-forge
  - gpytorch
dependencies:
  - python
  - numpy
  - pytorch
  - gpytorch
  - botorch
  - dill
  - click
  - scipy
  - scikit-learn
  - plotly
  - dash
  - pip
  - pip:
    - -e .