name: veropt
dependencies:
  - python
  - numpy
  - xarray
  - pytorch::pytorch
  - conda-forge::gpytorch
  - pytorch::botorch
  - dill
  - click
  - scipy
  - scikit-learn
  - pip
  - pip:
    - matplotlib
    - pyside6
    - -e .