name: veropt
channels:
  - conda-forge
  - gpytorch
dependencies:
  - python
  - numpy
  - xarray
  - pytorch
  - gpytorch
  - botorch
  - dill
  - click
  - scipy
  - scikit-learn
  - pip
  - pip:
    - matplotlib
    - pyside6
    - -e .