name: veropt_testing
channels:
  - conda-forge
  - gpytorch
dependencies:
  - python
  - numpy
  - pytorch
  - gpytorch
  - botorch
  - dill
  - scipy
  - mypy
  - flake8
  - pytest
  - pip
  - pip:
    - -e .