name: veropt_testing
channels:
  - conda-forge
  - gpytorch
dependencies:
  - python
  - numpy
  - xarray
  - pytorch
  - gpytorch
  - botorch
  - dill
  - click
  - scipy
  - scikit-learn
  - mypy
  - flake8
  - pytest
  - pip
  - pip:
    - matplotlib
    - pyside6
    - -e .