name: veropt_8
dependencies:
  - python=3.9.2
  - numpy=1.21.2
  - xarray=0.20.1
  - pytorch::pytorch=1.8.0
  - conda-forge::gpytorch=1.4.0
  - pytorch::botorch=0.4.0
  - dill=0.3.3
  - click=8.0.3
  - scipy=1.7.1
  - scikit-learn=0.24.1
  - pip=21.2.4
  - pip:
    - matplotlib==3.5.0
    - pyside6==6.2.1
    - -e .