# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on: [pull_request]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
        pip install .
    - name: Lint with flake8
      run: |
        pip install flake8
        # Note: Should be the same as in the local workflow. Please change both if you change this.
        # This will be re-enabled when veropt 1.0 releases
        # flake8 . --max-line-length=120

    - name: Type checking with mypy
      run: |
        pip install mypy
        # Note: Should be the same as in the local workflow. Please change both if you change this.
        # This will be re-enabled when veropt 1.0 releases
        # mypy veropt tests --disallow-untyped-defs --follow-untyped-imports

    - name: Test with pytest
      run: |
        pip install pytest
        pytest