# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on: [pull_request]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
        pip install .
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .

    - name: Type checking with mypy
      run: |
        pip install mypy
        mypy veropt tests examples

    - name: Test with pytest
      run: |
        pip install pytest
        pytest