name: Python Package using Conda

on: [pull_request]
on: [pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'


    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH


    - name: Install dependencies
      run: |
        pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
        conda env update --file environment.yml --name base
    - name: Lint with flake8
      run: |
        conda install flake8
        # Note: Should be the same as in the local workflow. Please change both if you change this.
        # This will be re-enabled when veropt 1.0 releases
        # flake8 . --max-line-length=120

    - name: Test with pytest
      run: |
        conda install pytest
        pytest

    - name: Type checking with mypy
      run: |
        conda install mypy
        # Note: Should be the same as in the local workflow. Please change both if you change this.
        # This will be re-enabled when veropt 1.0 releases
        # mypy veropt tests --disallow-untyped-defs --follow-untyped-imports
